### ISSUE TITLE
sepsis_cohort.py: KeyError: 'MechVent'

### ISSUE THREAD

**Issue by pathway** [microsoft/mimic_sepsis#9]
```
$ python preprocess.py
0
10000
20000
30000
40000
50000
60000
70000
80000
90000


$ python sepsis_cohort.py
Using TensorFlow backend.
Loading processed files created from database using "preprocess.py"
Filling-in missing ICUSTAY IDs in bacterio
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:31:17
Filling-in missing ICUSTAY IDs in bacterio - 2
0% [###########################   ] 100% | ETA: 00:00:23
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:03:43
Filling-in missing ICUSTAY IDs in ABx
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:26
Full ICU -- Finding presumed onset of infection according to sepsis3 guidelines
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:02:08
Full ICU -- Number of preliminary, presumed septic trajectories:  25367
Full ICU -- Replacing item_ids with column numbers from reference tables
 Full ICU --  Making an array with all unique charttime (1 per row) and all items in columns.
Traceback (most recent call last):
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'MechVent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sepsis_cohort.py", line 400, in <module>
    col = temp3.loc[ii, 'MechVent']
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1272, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1389, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1965, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/indexing.py", line 625, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/generic.py", line 3529, in xs
    return self[key]
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/robin/miniconda3/envs/tfgpu1/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'MechVent'
```
ubuntu 18.04
Python 3.6.7
Dataset: mimic-iii-clinical-database-1.4

Also, thanks for sharing this awesome resource!

**Comment by twkillian** [comment]
Hi @pathway! 

This is unfortunate to see given our recent PRs trying to align and fix bugs with this `MechVent` label.

Can you make sure you've pulled the most recent main branch? And ensure that the relevant line in `preprocess.py` matches this: https://github.com/microsoft/mimic_sepsis/blob/main/preprocess.py#L714

We also have a outstanding PR to finalize the refactoring to clean these kinds of errors up  (#8) . I double checked with that PR whether the code would run to completion and it did, so I'm not sure what's going on.

**Comment by pathway** [comment]
Thanks @twkillian :)

- yes Im using most recent main branch
- yes preprocess.py looks same

I added a breakpoint to see the dataframe:
```
> /usr/local/HAMMER/DYNAMIC/SRC/pathway/MIMIC/mimic_sepsis/sepsis_cohort.py(401)<module>()
-> col = temp3.loc[ii, 'MechVent']
(Pdb) temp3
         icustay_id     charttime  mechvent  extubated  selfextubated
2104142    294638.0  6.980521e+09         0          0              0
2104143    294638.0  6.980522e+09         0          0              0
```
- notice the column name is "mechvent" lowercase
- I see that column cases have been toggled more than once in recent commits.

I suspect what is happening is:
- some databases are case-insensitive.  I used postgres which dropped the table name case, see https://stackoverflow.com/a/20880247
- others are is case-sensitive, eg bigquery https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#case_sensitivity

Depending on database used in the first step we need slightly key case.

**Comment by pathway** [comment]
Considering a fix like https://github.com/pathway/mimic_sepsis/pull/1 , worked for me:

```
(tfgpu1) robin@thor:/SRC/pathway/MIMIC/pathway_mimic_sepsis/mimic_sepsis$ python sepsis_cohort.py 
Using TensorFlow backend.
Loading processed files created from database using "preprocess.py"
...loaded
Filling-in missing ICUSTAY IDs in bacterio
0% [##############################] 100% | ETA: 00:00:00^A#
Total time elapsed: 00:30:44
Filling-in missing ICUSTAY IDs in bacterio - 2
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:03:25
Filling-in missing ICUSTAY IDs in ABx
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:24
Full ICU -- Finding presumed onset of infection according to sepsis3 guidelines
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:01:54
Full ICU -- Number of preliminary, presumed septic trajectories:  25367
Full ICU -- Replacing item_ids with column numbers from reference tables
 Full ICU --  Making an array with all unique charttime (1 per row) and all items in columns.
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:53:28
Full ICU -- Handling outliers
Full ICU -- Doing sample and hold
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:07:58
Full ICU -- SAMPLE AND HOLD on RAW DATA
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:07:53
Full ICU -- Data combination
sepsis_cohort.py:751: RuntimeWarning: Mean of empty slice
  else:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:39:09
FULL ICU -- CONVERTING TO TABLE AND DELETE VARIABLES WITH EXCESSIVE MISSINGNESS
Full ICU -- Doing linear interpolation where missingness is low (kNN imputation doesnt work if all rows have missing values)
Full ICU -- KNN imputation
0% [#                         ] 100% | ETA: 00:00:01Imputing row 1/9999 with 24 missing, elapsed time: 25.648
Imputing row 101/9999 with 2 missing, elapsed time: 25.720
Imputing row 201/9999 with 30 missing, elapsed time: 25.790
...
Imputing row 6401/6526 with 12 missing, elapsed time: 11.648
Imputing row 6501/6526 with 9 missing, elapsed time: 11.692
Sepsis Cohort -- Making trajectory data
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:01:15
Sepsis Cohort -- Making final output file
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06
```
... but I guess would need to toggle colname_lower flag depending on the db:

https://github.com/pathway/mimic_sepsis/pull/1/files#diff-cc7d08a4ac5b9883528e4d044f6b2821c7cac3fc5999ccd5990560d1052c8fb3R192

Could be added as a cmd line arg.

Does this approach seem useful?

**Comment by fatemi** [comment]
@pathway Can you confirm if the new PR fixed the problem?

**Comment by pathway** [comment]
@fatemi I started the PR, but I dont think its complete.

The PR seems to fix the problem for my own setup (using postgres) but I dont think it would fix for certain other databases (see above regarding case sensitivity of databases) so it should not be merged yet.

Seeking feedback on my comments above.  Thanks!

**Comment by twkillian** [comment]
Hi @pathway we've received a couple of other emails about this. One suggestion we received was to wrap the `MechVent` label in quotes within `preprocess.py`.

That would change https://github.com/microsoft/mimic_sepsis/blob/main/preprocess.py#L714 to:
```
) as "MechVent"
```

There's a similar issue at: https://github.com/microsoft/mimic_sepsis/blob/main/preprocess.py#L722 but could be changed/improved again by wrapping in quotes:
```
as "Extubated"
```

Would this resolve the issues you've had?

**Comment by woowonjin** [comment]
In my case, I can resolve the same problem by revising all "MechVent" and "Extubated" to lowercase.

**Comment by twkillian** [comment]
Thanks for the confirmation @woowonjin. I think that it'll just be easier to cut out all camel case naming conventions and just using all lowercase. I'll go ahead and make the changes and push a PR.

**Comment by woowonjin** [comment]
@twkillian  I saw your commit code. But i didn't revise the code in preprocess.py actually.. However if your revision can resolve issue, that's enough. It sounds cool !!
